Repository Algorithm-study-s10/Algorithm_Study, pull requests merged in 2025-04, with the labels that each got.

#52 w08_거짓말 - 혜선
  src/main/java/org/example/yhs3237/w08_lie/baekjoon1043.java
Labels: 그래프, 유니온파인드

#53 w08_거짓말 - 선민
  src/main/java/org/example/seonmin98/w08_거짓말/Main.java
Labels: 그래프, 유니온파인드

#54 w08_거짓말 - 예린
  src/main/java/org/example/rt8632/w08_Lie/boj_1043.java
Labels: 그래프, 유니온파인드

#55 w08_알고스팟 - 혜선
  .idea/misc.xml
  src/main/java/org/example/yhs3237/w08_algoSpot/baekjoon1261.java
Labels: BFS, 그래프

#56 w08_알고스팟 - 선민
  src/main/java/org/example/seonmin98/w08_알고스팟/Main.java
Labels: 우선순위큐, 다익스트라

#57 w09_알고 스팟 - 예린
  src/main/java/org/example/rt8632/w08_Lie/boj_1043.java
  src/main/java/org/example/rt8632/w09_AlgoSpot/boj_1261.java
Labels: BFS, 우선순위큐

#59 w09_동전문제 - 선민
  src/main/java/org/example/seonmin98/w09_동전문제/Main.java
Labels: DP

#60 w09_동전 - 예린
  src/main/java/org/example/rt8632/w09_Coin/boj_9084.java
Labels: DP

#61 w09_공유기 설치 - 혜선
  src/main/java/org/example/yhs3237/w09_setRouter/baekjoon2110.java
Labels: 이분탐색

#64 w10_탈출 - 혜선
  src/main/java/org/example/yhs3237/w10_escape/baekjon3055.java
Labels: BFS, 시뮬레이션, 그래프

#65 w10_탈출 - 선민
  src/main/java/org/example/seonmin98/w10_탈출/Main.java
Labels: 연결리스트, BFS

#66 w10_탈출 - 예린
  src/main/java/org/example/rt8632/w10_Escape/boj_3055.java
  src/main/java/org/example/rt8632/w10_Escape/boj_3055_v2.java
Labels: BFS

#67 w10_팰린드롬 만들기 - 혜선
  src/main/java/org/example/yhs3237/w10_palindrome/baekjoon1213.java
  src/main/java/org/example/yhs3237/w10_palindrome/baekjoon1213_backtracking.java
Labels: 그리디

#68 w10_팰린드롬만들기 - 선민
  src/main/java/org/example/seonmin98/w10_팰린드롬만들기/Main.java
Labels: 스택, 큐

#69 w10_팰린드롬 만들기 - 예린
  src/main/java/org/example/rt8632/w10_MakePalindrome/boj_1213.java
Labels: 백트래킹

#71 w11_주사위 굴리기 - 혜선
  src/main/java/org/example/yhs3237/w11_rollDice/baekjoon14499.java
Labels: 시뮬레이션

#72 w11_주사위굴리기 - 선민
  src/main/java/org/example/seonmin98/w11_주사위굴리기/Main.java
Labels: 시뮬레이션

#73 w11_주사위 굴리기 - 예린
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  src/main/java/org/example/rt8632/w11_RollTheDice/boj_14499.java
Labels: 시뮬레이션

#75 w11_해킹 - 혜선
  src/main/java/org/example/yhs3237/w11_hacking/baekjoon10282.java
Labels: 그래프, 다익스트라

#76 w11_해킹 - 선민
  src/main/java/org/example/seonmin98/w11_해킹/Main.java
Labels: 다익스트라

#77 w11_해킹 - 예린
  src/main/java/org/example/rt8632/w11_Hacking/boj_10282.java
Labels: 다익스트라
