Repository Algorithm-study-s10/Algorithm_Study, pull requests merged in 2025-03, with the labels that each got.

#25 w03_연산자 끼워넣기 - 선민
  src/main/java/org/example/seonmin98/w03_연산자끼워넣기/Main.java
Labels: 재귀, 백트래킹

#26 w03_연산자 끼워넣기 - 혜선
  .idea/gradle.xml
  .idea/uiDesigner.xml
  src/main/java/org/example/yhs3237/w03_addOperator/baekjoon14888.java
Labels: 재귀, 백트래킹

#27 w03_연산자끼워넣기 - 이루
  src/main/java/org/example/iroo2001/w03_연산자끼워넣기/Main.java
Labels: DFS, 재귀

#28 w04_외계인의기타연주 - 선민
  src/main/java/org/example/seonmin98/w04_외계인의기타연주/Main.java
Labels: 배열, 스택

#29 w04_외계인의 기타 연주 - 혜선
  src/main/java/org/example/yhs3237/TwoPointer.java
  src/main/java/org/example/yhs3237/w04_guitar/baekjoon2841.java
Labels: 배열, 스택

#30 w04_외계인의 기타 연주 - 이루
  src/main/java/org/example/iroo2001/w04_외계인의기타연주/Main.java
Labels: 배열, 스택

#31 w04_로또 - 선민
  src/main/java/org/example/seonmin98/w04_로또/Main.java
Labels: 배열, 재귀

#32 w04_로또 - 이루
  src/main/java/org/example/iroo2001/w04_로또/Main.java
Labels: 배열, 재귀

#33 w04_로또 - 혜선
  src/main/java/org/example/yhs3237/w04_lotto/baekjoon6603.java
Labels: 재귀, 백트래킹

#34 w04_로또 - 예린
  src/main/java/org/example/rt8632/w04_Lotto/boj_6603.java
Labels: 재귀, 백트래킹

#35 w05_설탕 배달 - 혜선
  src/main/java/org/example/yhs3237/w05_sugarDelivery/baekjoon2839_dp.java
  src/main/java/org/example/yhs3237/w05_sugarDelivery/baekjoon2839_for.java
Labels: DP

#36 w05_설탕배달 - 이루
  src/main/java/org/example/iroo2001/w05_설탕배달/Main.java
Labels: DP, 그리디

#37 w05_설탕 배달 - 예린
  src/main/java/org/example/rt8632/w05_SugarDelivery/boj_2839.java
Labels: 그리디

#38 w05_설탕배달 - 선민
  src/main/java/org/example/seonmin98/w05_설탕배달/Main.java
Labels: DP

#39 w05_baseball - 선민
  src/main/java/org/example/seonmin98/w05_baseball/Main.java
Labels: 재귀, 시뮬레이션

#40 w05_baseball - 혜선
  src/main/java/org/example/yhs3237/w05_baseball/baekjoon17281.java
Labels: 백트래킹, 시뮬레이션

#41 w06_소문난 칠공주 - 혜선
  src/main/java/org/example/yhs3237/w06_sevenPrincess/baekjoon1941.java
Labels: BFS, DFS, 백트래킹

#42 w06_소문난칠공주 - 이루
  src/main/java/org/example/iroo2001/w06_소문난칠공주/Main.java
Labels: 큐, BFS, 백트래킹, 그래프

#43 w06_케빈베이컨의6단계 - 선민
  src/main/java/org/example/seonmin98/w06_케빈베이컨의6단계/Main.java
Labels: 배열, DP

#44 w06_케빈 베이컨의 6단계 법칙
  src/main/java/org/example/rt8632/w06_KevinBacon6Level/boj_1389.java
Labels: 큐, BFS

#45 w06_케빈 베이컨의 6단계 법칙 - 혜선
  src/main/java/org/example/yhs3237/w06_kevinB/baekjoon1389.java
Labels: 그래프

#46 w07_숨바꼭질 - 혜선
  src/main/java/org/example/yhs3237/w07_hidAndSeek/baekjoon1697.java
Labels: BFS

#47 w07_숨바꼭질 - 선민
  src/main/java/org/example/seonmin98/w07_숨바꼭질/Main.java
Labels: 큐, BFS

#48 w07_숨바꼭질 - 예린
  src/main/java/org/example/rt8632/w07_HideAndSeek/boj_1697.java
Labels: BFS

#49 w07_등굣길 - 혜선
  src/main/java/org/example/yhs3237/w07_goSchool/Solution.java
Labels: DP

#50 w07_등굣길 - 예린
  src/main/java/org/example/rt8632/w07_goSchool/programmers_goSchool.java
Labels: DP

#51 w07_등굣길 - 선민
  src/main/java/org/example/seonmin98/w07_등굣길/Solution.java
Labels: DP
